language: objective-c
os: osx
osx_image: xcode11.5
xcode_project: AcessibilityFaceMouse/AcessibilityFaceMouse.xcodeproj
xcode_scheme: AcessibilityFaceMouse
xcode_destination: platform=iOS Simulator,OS=11.3,name=iPhone X
