language: objective-c
os: osx
osx_image: xcode11.3

script:
- set -o pipefail
- xcodebuild build -project AcessibilityFaceMouse/AcessibilityFaceMouse.xcodeproj -scheme "AcessibilityFaceMouse" -sdk iphonesimulator | xcpretty

