language: objective-c

osx_image: xcode10.1
env:
  matrix:
    - TEST_SDK=iphonesimulator12.1 OS=13.1 NAME='iPhone XR'
    - TEST_SDK=iphonesimulator12.1 OS=13.1 NAME='iPhone 7'

script:
  - set -o pipefail && xcodebuild clean build test -project AcessibilityFaceMouse/AcessibilityFaceMouse.xcodeproj -scheme "AcessibilityFaceMouse" -sdk iphonesimulator -destination "platform=iOS Simulator,OS=13.1,name=iPhone 8" ONLY_ACTIVE_ARCH=YES


