language: swift
os: osx
osx_image: xcode11.3
script:
  xcodebuild clean build test -project AcessibilityFaceMouse/AcessibilityFaceMouse.xcodeproj -scheme "AcessibilityFaceMouse" -sdk iphonesimulator -destination "platform=iOS Simulator,OS=13.1,name=iPhone 8" ONLY_ACTIVE_ARCH=NO

notifications:
email:
  recipients:
    - j.batista.damasceno@icloud.com
  on_failure: always # default: always
